channels:
  - defaults
  - pytorch
  - nvidia
  - fastai
  - conda-forge
dependencies:
  - python=3.8.18
  - joblib=1.3.2
  - numpy=1.23.5
  - pandas=2.0.3
  - scikit-learn=1.3.2
  - scikit-learn-intelex=2024.1.0
  - fastai=2.7.14
  - pytorch-cuda=11.8
  - pytorch=2.2.0
  - torchvision=0.17.0
  - torchaudio=2.2.0
  - pip=24.0
  - pip:
      - Cython==3.0.8
      - blosc2==2.0.0
      - azureml-defaults==1.55.0
      - azureml-dataprep[pandas]
      - azureml-core
      - azure-core
      - azureml-pipeline==1.55.0
      - azureml-widgets==1.55.0
name: lwc_python
